// Command docsgen emits the CLI and environment-variable reference
// documentation from the real cli.App, so the docs cannot drift from the
// binary. Run via `make docs-gen`.
//
// It lives in the root module rather than under docs/ because docs/ carries
// its own go.mod for the Hugo module, which would put a generator placed there
// in a module that cannot import github.com/mudler/edgevpn/cmd.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/urfave/cli/v2"

	"github.com/mudler/edgevpn/cmd"
)

const outDir = "docs/content/en/docs/reference"

func main() {
	// The version is irrelevant to the generated output and must be fixed,
	// otherwise the CI drift check would fail on every release.
	app := cmd.NewApp("")

	if err := run(app); err != nil {
		fmt.Fprintln(os.Stderr, "docs generate:", err)
		os.Exit(1)
	}
}

func run(app *cli.App) error {
	cliDir := filepath.Join(outDir, "cli")
	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return err
	}

	bindings := map[string][]envBinding{}
	collectEnv(bindings, app.Flags, "global")

	// Every page is rendered up front, so the directory is only modified once
	// the full output is known to be in hand. Rendering into memory first is
	// what lets the prune below skip files it is about to rewrite; a
	// delete-then-write pass could empty the directory and then fail.
	pages := map[string]string{}

	// Index page, carrying the root flag table.
	var idx strings.Builder
	idx.WriteString("---\ntitle: \"CLI\"\nlinkTitle: \"CLI\"\nweight: 10\ndescription: >\n  Every EdgeVPN command and flag.\n---\n\n")
	idx.WriteString(banner + "\n\n")
	idx.WriteString("Running `edgevpn` with no subcommand starts the VPN.\n\n## Global flags\n\n")
	idx.WriteString(renderFlagTable(app.Flags))
	idx.WriteString("\n## Commands\n\n")
	for _, c := range app.Commands {
		fmt.Fprintf(&idx, "- [`%s`](%s/) — %s\n", c.Name, c.Name, escapeCell(c.Usage))
	}
	pages["_index.md"] = idx.String()

	for i, c := range app.Commands {
		pages[c.Name+".md"] = renderCommandPage(c, (i+1)*10)
		collectEnv(bindings, c.Flags, c.Name)
		for _, sub := range c.Subcommands {
			collectEnv(bindings, sub.Flags, c.Name+" "+sub.Name)
		}
	}

	// Drop pages for commands that no longer exist, so a removed command does
	// not leave a stale page behind — the drift gate would never catch it.
	fresh := make(map[string]bool, len(pages))
	for name := range pages {
		fresh[name] = true
	}
	foreign, err := pruneStale(cliDir, fresh)
	if err != nil {
		return err
	}
	for _, name := range foreign {
		fmt.Fprintf(os.Stderr,
			"docs generate: leaving %s alone: it is not generated (no %q banner)\n",
			filepath.Join(cliDir, name), "Generated by internal/docsgen")
	}

	names := make([]string, 0, len(pages))
	for name := range pages {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := os.WriteFile(filepath.Join(cliDir, name), []byte(pages[name]), 0o644); err != nil {
			return err
		}
	}

	return os.WriteFile(
		filepath.Join(outDir, "environment-variables.md"),
		[]byte(renderEnvVarPage(bindings)), 0o644)
}

// pruneStale removes generated markdown pages in dir that are not in fresh.
//
// It only ever deletes files carrying the generator's banner, so a hand-written
// page dropped into the directory survives — the previous unconditional
// `os.Remove` over `*.md` would have destroyed it silently. Files it declines
// to delete are returned by name so the caller can report them rather than let
// them accumulate unnoticed. Files that are about to be rewritten are left in
// place, so a failure part-way through writing cannot leave the tree emptied.
func pruneStale(dir string, fresh map[string]bool) ([]string, error) {
	entries, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return nil, err
	}

	var foreign []string
	for _, p := range entries {
		name := filepath.Base(p)
		if fresh[name] {
			continue
		}
		content, err := os.ReadFile(p)
		if err != nil {
			return nil, err
		}
		if !bytes.Contains(content, []byte(banner)) {
			foreign = append(foreign, name)
			continue
		}
		if err := os.Remove(p); err != nil {
			return nil, err
		}
	}
	sort.Strings(foreign)
	return foreign, nil
}

func collectEnv(into map[string][]envBinding, flags []cli.Flag, command string) {
	for _, f := range flags {
		df, ok := documented(f)
		if !ok {
			continue
		}
		names := f.Names()
		if len(names) == 0 {
			continue
		}
		def := defaultText(df)
		for _, env := range df.GetEnvVars() {
			into[env] = append(into[env], envBinding{
				Flag:    "--" + names[0],
				Command: command,
				Default: def,
			})
		}
	}
}
