package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/urfave/cli/v2"
)

const banner = "<!-- Generated by internal/docsgen. Do not edit; run `make docs-gen`. -->"

// envBinding records one place an environment variable is read from.
type envBinding struct {
	Flag    string
	Command string
	Default string
}

// escapeCell makes a string safe inside a markdown table cell. Several real
// usage strings contain "|" (the ownership flag lists its modes that way),
// which would otherwise split the row into extra columns.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}

// documented reports whether a flag should appear in the reference, and
// returns the documentation view of it.
//
// IsVisible lives on cli.VisibleFlag, not on cli.DocGenerationFlag, so the two
// interfaces have to be asserted separately. A flag that implements neither is
// skipped rather than rendered with empty columns.
func documented(f cli.Flag) (cli.DocGenerationFlag, bool) {
	df, ok := f.(cli.DocGenerationFlag)
	if !ok {
		return nil, false
	}
	if vf, ok := f.(cli.VisibleFlag); ok && !vf.IsVisible() {
		return nil, false
	}
	return df, true
}

// machineSpecific lists path prefixes that differ between the machine the docs
// were generated on and the machine the CI drift gate runs on. cmd.stateDir()
// derives --privkey-cache-dir and --lease-dir from the caller's home
// directory, so without this the generated output would never be reproducible.
var machineSpecific = func() [][2]string {
	var subs [][2]string
	if home, err := os.UserHomeDir(); err == nil && home != "" && home != "/" {
		subs = append(subs, [2]string{home, "$HOME"})
	}
	if wd, err := os.Getwd(); err == nil && wd != "" && wd != "/" {
		subs = append(subs, [2]string{wd, "."})
	}
	return subs
}()

// normalizeDefault strips machine-specific prefixes out of a default value.
func normalizeDefault(s string) string {
	for _, sub := range machineSpecific {
		s = strings.ReplaceAll(s, sub[0], sub[1])
	}
	return s
}

// defaultText returns the documented default for a flag: the explicit
// DefaultText when the flag sets one, otherwise its value, normalised so the
// output does not depend on where it was generated. It returns "" when the
// flag has no default.
func defaultText(df cli.DocGenerationFlag) string {
	def := df.GetDefaultText()
	if def == "" {
		def = df.GetValue()
	}
	return normalizeDefault(def)
}

func flagNames(f cli.Flag) string {
	names := f.Names()
	out := make([]string, 0, len(names))
	for _, n := range names {
		if len(n) == 1 {
			out = append(out, "`-"+n+"`")
		} else {
			out = append(out, "`--"+n+"`")
		}
	}
	return strings.Join(out, ", ")
}

// renderFlagTable renders a markdown table for the visible flags.
func renderFlagTable(flags []cli.Flag) string {
	var b strings.Builder
	b.WriteString("| Flag | Default | Environment | Description |\n")
	b.WriteString("|---|---|---|---|\n")

	rows := 0
	for _, f := range flags {
		df, ok := documented(f)
		if !ok {
			continue
		}
		def := defaultText(df)
		if def == "" {
			def = "—"
		} else {
			def = "`" + escapeCell(def) + "`"
		}

		env := "—"
		if vars := df.GetEnvVars(); len(vars) > 0 {
			quoted := make([]string, len(vars))
			for i, v := range vars {
				quoted[i] = "`" + v + "`"
			}
			env = strings.Join(quoted, ", ")
		}

		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
			flagNames(f), def, env, escapeCell(df.GetUsage()))
		rows++
	}
	if rows == 0 {
		return "_This command takes no flags of its own._\n"
	}
	return b.String()
}

// renderCommandPage renders one Hugo page for a command.
func renderCommandPage(c *cli.Command, weight int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %q\nlinkTitle: %q\nweight: %d\n", c.Name, c.Name, weight)
	// An empty folded scalar would leave "description: >" dangling and break
	// the front matter, so the key is only emitted when there is a usage line.
	if u := escapeCell(c.Usage); u != "" {
		fmt.Fprintf(&b, "description: >\n  %s\n", u)
	}
	b.WriteString("---\n\n")
	b.WriteString(banner + "\n\n")

	if len(c.Aliases) > 0 {
		quoted := make([]string, len(c.Aliases))
		for i, a := range c.Aliases {
			quoted[i] = "`" + a + "`"
		}
		fmt.Fprintf(&b, "Aliases: %s\n\n", strings.Join(quoted, ", "))
	}
	if c.Description != "" && c.Description != c.Usage {
		fmt.Fprintf(&b, "%s\n\n", c.Description)
	}

	fmt.Fprintf(&b, "```\nedgevpn %s [options]\n```\n\n", c.Name)
	b.WriteString("## Flags\n\n")
	b.WriteString(renderFlagTable(c.Flags))

	for _, sub := range c.Subcommands {
		fmt.Fprintf(&b, "\n## `%s %s`\n\n", c.Name, sub.Name)
		if sub.Usage != "" {
			fmt.Fprintf(&b, "%s\n\n", sub.Usage)
		}
		b.WriteString(renderFlagTable(sub.Flags))
	}
	return b.String()
}

// renderEnvVarPage renders the environment-variable cross-reference.
//
// The variable names are sorted so the output is byte-for-byte reproducible;
// Go's randomised map iteration would otherwise make the CI drift gate fail at
// random.
func renderEnvVarPage(bindings map[string][]envBinding) string {
	var b strings.Builder
	b.WriteString("---\ntitle: \"Environment variables\"\nlinkTitle: \"Environment variables\"\nweight: 20\ndescription: >\n  Every environment variable EdgeVPN reads, and the flag it corresponds to.\n---\n\n")
	b.WriteString(banner + "\n\n")
	b.WriteString("Environment variables are read when the corresponding flag is not passed.\n\n")
	b.WriteString("| Variable | Flag | Command | Default |\n|---|---|---|---|\n")

	names := make([]string, 0, len(bindings))
	for k := range bindings {
		names = append(names, k)
	}
	sort.Strings(names)

	for _, name := range names {
		for _, bind := range bindings[name] {
			def := bind.Default
			if def == "" {
				def = "—"
			} else {
				def = "`" + escapeCell(def) + "`"
			}
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n",
				name, bind.Flag, bind.Command, def)
		}
	}
	return b.String()
}
